[Service]
NoNewPrivileges=true
PrivateTmp=true
TemporaryFileSystem=/tmp:rw,nosuid,nodev,noexec,size=128M
ProtectSystem=full
ProtectHome=read-only
ReadWritePaths=/var/www/Traffic/traffic-app /home/tony/.cache
RestrictSUIDSGID=true
LockPersonality=true
